<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class MethodologySeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $methodology = [[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Головной мозг',
            'short' => 'ГМ',
            'check_name' => 'ГМ',
            'time' => '20',
            'price' => '3800',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Артерии головного мозга без контраста',
            'short' => 'Артерии ГМ',
            'check_name' => 'Артерии ГМ',
            'time' => '10',
            'price' => '2500',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Вены и синусы головного мозга без контраста',
            'short' => 'Вены ГМ',
            'check_name' => 'Вены ГМ',
            'time' => '10',
            'price' => '2500',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Гипофиз',
            'short' => '',
            'check_name' => 'Гипофиз',
            'time' => '20',
            'price' => '3500',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Орбиты',
            'short' => '',
            'check_name' => 'Орбиты',
            'time' => '15',
            'price' => '3300',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Височно-нижнечелюстные суставы',
            'short' => 'ВНЧС',
            'check_name' => 'ВНЧС',
            'time' => '20',
            'price' => '3300',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 2,
            'name' => 'Шея (мягкие ткани, щитовидная железа, лимфоузлы)',
            'short' => 'Шея',
            'check_name' => 'Шея',
            'time' => '20',
            'price' => '3100',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 3,
            'name' => 'Средостение',
            'short' => '',
            'check_name' => 'Сред',
            'time' => '20',
            'price' => '3300',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 4,
            'name' => 'Верхний этаж живота',
            'short' => 'ВЭЖ',
            'check_name' => 'ВЭЖ',
            'time' => '35',
            'price' => '4500',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 4,
            'name' => 'Малый таз',
            'short' => 'Таз',
            'check_name' => 'Таз',
            'time' => '35',
            'price' => '4100',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 5,
            'name' => 'Тазобедренный сустав',
            'short' => '',
            'check_name' => 'ТБС',
            'time' => '15',
            'price' => '3700',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 5,
            'name' => 'Коленный сустав',
            'short' => '',
            'check_name' => 'КС',
            'time' => '30',
            'price' => '3700',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 6,
            'name' => 'Шейный отдел позвоночника',
            'short' => 'ШОП',
            'check_name' => 'ШОП',
            'time' => '15',
            'price' => '3800',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 6,
            'name' => 'Грудной отдел позвоночника',
            'short' => 'ГОП',
            'check_name' => 'ГОП',
            'time' => '15',
            'price' => '3800',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 6,
            'name' => 'Пояснично-крестцовый отдел позвоночника',
            'short' => 'ПОП',
            'check_name' => 'ПОП',
            'time' => '15',
            'price' => '3800',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Придаточные пазухи носа',
            'short' => '',
            'check_name' => 'ППН',
            'time' => '15',
            'price' => '2500',
            'contrast' => '0',
        ],[
            'method_id' => 1,
            'zone_id' => 1,
            'name' => 'Внутреннее ухо',
            'short' => '',
            'check_name' => '',
            'time' => '15',
            'price' => '3300',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 9,
            'name' => 'Эхокардиография',
            'short' => 'Эхокардиография',
            'check_name' => 'Эхокардиография',
            'time' => '10',
            'price' => '750',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 9,
            'name' => 'УЗИ органов брюшной полости с ЦДК',
            'short' => 'ОБП',
            'check_name' => 'ОБП',
            'time' => '10',
            'price' => '550',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 9,
            'name' => 'УЗИ органов мочевыделительной системы с ЦДК',
            'short' => 'МВС',
            'check_name' => 'МВС',
            'time' => '10',
            'price' => '500',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 9,
            'name' => 'УЗИ щитовидной железы с ЦДК',
            'short' => 'ЩЖ',
            'check_name' => 'ЩЖ',
            'time' => '10',
            'price' => '500',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 9,
            'name' => 'УЗИ молочной железы с ЦДК',
            'short' => 'МЖ',
            'check_name' => 'мол. желез',
            'time' => '10',
            'price' => '500',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 12,
            'name' => 'Кардиокомплекс (ЭхоКГ+ЭКГ+Холтер )',
            'short' => 'КК',
            'check_name' => 'Кардиокомплекс',
            'time' => '40',
            'price' => '1900',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 12,
            'name' => 'Женский комплекс (ТВ)',
            'short' => 'ЖК-ТВ',
            'check_name' => 'Женский Комплекс',
            'time' => '30',
            'price' => '2400',
            'contrast' => '0',
        ],[
            'method_id' => 2,
            'zone_id' => 12,
            'name' => 'Мужской комплекс',
            'short' => 'МК',
            'check_name' => 'Мужской Комплекс',
            'time' => '30',
            'price' => '1800',
            'contrast' => '0',
        ]];
        DB::table('mskt_research_methodologys')->insert($methodology);
    }
}
